version: '3'
services:
  package:
    image: drupsys/php-package-alpine
    container_name: servicer-package
    volumes:
    - .:/app

  linter:
    image: drupsys/php-linter
    container_name: servicer-linter
    volumes:
    - ./src:/code/src
    - ./tests/acceptance:/code/acceptance
    - ./tests/functional:/code/functional
    - ./tests/unit:/code/unit
    - ./linter/php_cs.php:/code/.php_cs.dist
    - ./linter/mvf_ruleset.xml:/code/mvf_ruleset.xml

  coverage:
    build: .
    container_name: servicer-coverage
    ports:
      - 7000:80
    volumes:
    - .:/code
    - ./tests/_output/coverage:/usr/share/nginx/html
